// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";

const fontSans = Syne({
  subsets: ["latin"],
  variable: "--font-sans",
});

// const fontSerif = Georgia({
//   subsets: ["latin"],
//   variable: "--font-serif",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ${fontSerif.variable} */}
      <body className={`${fontSans.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}